version: '3.8'

services:
  api1:
    build: .
    container_name: node_api1
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: utec
      DB_DATABASE: scooter_management
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
