version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_c
    environment:
      MYSQL_ROOT_PASSWORD: utec
      MYSQL_DATABASE: scooter_management
    ports:
      - "8005:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Montamos el script SQL
    networks:
      - app-network

  api:
    build: .
    container_name: node_api
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: utec
      DB_DATABASE: scooter_management
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge